### ISSUE TITLE
Connection to Hub after login

### ISSUE THREAD

**Issue by DominikBauer1** [PascalKoe/Connect4#4]
Wenn man ohne sich einzuloggen eine Game Starten will, wird man aufgefordert sich einzuloggen.
Man verbindet sich jedoch jetzt noch nihct mit dem Hub, oder ? Sondern erst wenn man in einem Game ist, oder ?
Kann an das ändern, so das man sich direkt nach dem einloggen verbindet?

**Comment by PascalKoe** [comment]
Der Hub hat bisher zwei Aufgaben. Zu einem das Updaten des Spielfelds beim Spielen und zum Anderen um die aktuellen Nutzer die Online sind anzuzeigen. Ich meine der Hub ist auch nur für Authentifizierte zugänglich.

StartGame ist im Moment (war zu testzwecken) auf nur Angemeldete freigegeben. Ich würde sagen, das passt auch so, sprich man muss angemeldet sein zum Spielen. Das gleiche sollte für die Game Seite gelten was aber noch nicht der Fall ist.

Geregelt ob nur angemeldete die Seite betreten werden kann wird mit einer sogenannten DataAnnotation geregelt. In der .cshtml.cs Datei zu der jeweiligen Seite muss bei der Klassendefinition direkt davor [Authorize] angegeben werden.
Es kann auch noch verfeinert werden mit zum Beispiel Rollenbasierter Autorisierung.

Theoretisch sollte wenn ein User nicht die Berechtigung hat auf eine Forbidden Seite weitergeleitet werden. Wenn man nicht angemeldet ist aber auf eine Seite zugreifen will, welche nur für Authentifizierte zugänglich ist, dann sollte man auf die Login Form weitergeleitet werden. Nach dem Login wird man wieder auf die ursprüngliche Seite weitergeleitet.
